name: Deploy to GitHub Pages

# Run this script securely every time `main` branch is updated
on:
  push:
    branches: ["main"]
  workflow_dispatch:

# Give GitHub Actions permission to publish to Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install Dependencies
        run: npm ci
        
      # Automatically pass the correct base URL based on the GitHub repository name using vite build --base flag
      - name: Build Vite App
        run: npm run build -- --base=/${{ github.event.repository.name }}/
        
      - name: Setup Pages
        uses: actions/configure-pages@v5
        with:
          enablement: true
        
      - name: Upload dist folder artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'
          
      - name: Deploy to GitHub Pages!
        id: deployment
        uses: actions/deploy-pages@v4
